### ISSUE TITLE
接入GPS后报错

### ISSUE THREAD

**Issue by ZOUJIASHUAI** [JokerJohn/LIO_SAM_6AXIS#100]
<img width="722" alt="image" src="https://github.com/user-attachments/assets/4549e077-4e53-42c2-bac8-97b8a26678ad" />

**Comment by ZOUJIASHUAI** [comment]
是否是因为 gps 协方差不能为0导致？

**Comment by ZOUJIASHUAI** [comment]
@JokerJohn 帮忙看下老板

**Comment by JokerJohn** [comment]
@ZOUJIASHUAI 你的log中协方差为0，你可以设置一个固定的，比如0.1，这样就不会报错了
