### ISSUE TITLE
time synchronization 

### ISSUE THREAD

**Issue by xuzhen80** [JokerJohn/LIO_SAM_6AXIS#11]
What kind of time synchronization does your IMU and lidar（hesai） use, hardware synchronization or software synchronization？

Is there any recommendation for hardware synchronization？

**Comment by JokerJohn** [comment]
For this kind of sensor kit, the dataset was collected by the HILTI origanizers, maybe you can get the related information here [Hilti-SLAM-Challenge](https://github.com/Hilti-Research/Hilti-SLAM-Challenge-2022)
