### ISSUE TITLE
if this code only have gps and imu without  lidar，can it  work and out pose？

### ISSUE THREAD

**Issue by cudnn** [JokerJohn/LIO_SAM_6AXIS#15]

**Comment by JokerJohn** [comment]
Of course not, this system will have no output poses without any kind of sensor in lidar and IMU.

**Comment by deepuav** [comment]
thanks! but i think ekf(gps+9dof) can out pose.

**Comment by zarathustr** [comment]
@deepuav We do not work on integrated navigation of GNSS/MARG sensors, which is not the essential part of Lidar-Inertial Odometry.
