### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by hongSS0919** [JokerJohn/LIO_SAM_6AXIS#18]
十分抱歉，上一个问题我不小心点close了，如果打扰到你十分抱歉。
你好大佬，首先十分感谢你的开源，谢谢。但我有些问题哈，我看过原版的lio_sam,也看了你的，对于9轴imu而言，它多了个orientation这个姿态量，但是我看原版的代码，它这个量好像用处不是特别大，甚至我觉得这个量并没有用上，具体原因看updateInitialGuess()这个函数，初始位姿还是用odom的。
所以，我是不是可以理解成原版的lio_sam其实也能用六轴imu？
ps：可能是我遗漏了哪里，如果错误希望可以指点一下，十分感谢。

**Comment by JokerJohn** [comment]
可以阅读这个文档，里面做出了解释。 https://github.com/JokerJohn/LIO_SAM_6AXIS/blob/main/doc/adaption.md

**Comment by hongSS0919** [comment]
嗯嗯，看到了，十分感谢，祝好。
