### ISSUE TITLE
rtk_gnss 相关问题

### ISSUE THREAD

**Issue by lucianzhong** [JokerJohn/LIO_SAM_6AXIS#20]
您好,非常感谢您这个开源项目. 
请问如果用一个 rtk_gnss,并且全程rtk结果都很精确, 那么是不是可以直接用 mapping时候的位姿做 localization, 而不需要先mapping,然后 scan_to_map做定位呢?
祝好

**Comment by JokerJohn** [comment]
rtk全程高精度，那么就全程使用rtk，无需slam。如果rtk部分区域高精度，可以将这些区域的rtk姿态作为强先验，结合SLAM。

**Comment by lucianzhong** [comment]
收到,谢谢
