### ISSUE TITLE
z形跳跃

### ISSUE THREAD

**Issue by legoo-jie** [JokerJohn/LIO_SAM_6AXIS#21]
您好，在自己录制的室内数据包后运行出现轨迹的z形跳跃，请问这种情况如何解决呢？

**Comment by JokerJohn** [comment]
有相关RVIZ截图吗，你的轨迹跳跃指的是橙色的IMU预测轨迹还是lidar odmetry的轨迹？

**Comment by legoo-jie** [comment]
![Screenshot from 2022-09-16 16-19-40](https://user-images.githubusercontent.com/111752903/190592573-35349338-f9aa-4bbf-be06-3aa13a2d750e.png)
抱歉回复的这么晚，跳跃的轨迹是imu的轨迹，终端显示速度过大，Imu重启。其中录制的数据包是在实验室单个房间的小场景下录制的数据。

**Comment by JokerJohn** [comment]
> ![Screenshot from 2022-09-16 16-19-40](https://user-images.githubusercontent.com/111752903/190592573-35349338-f9aa-4bbf-be06-3aa13a2d750e.png) 抱歉回复的这么晚，跳跃的轨迹是imu的轨迹，终端显示速度过大，Imu重启。其中录制的数据包是在实验室单个房间的小场景下录制的数据。

你这个应该是IMU雷达外参没设置好，其实只要外参R设置好了，即雷达和IMU坐标轴对齐了，就不会出现你这种情况。你需要检查一些外参。
