### ISSUE TITLE
[hkust campus dataset] why the optimized trajectory displayed in GoogleMaps，pass through green belts and buildings

### ISSUE THREAD

**Issue by cacao1987** [JokerJohn/LIO_SAM_6AXIS#23]
Why does the optimized trajectory, displayed in Google Maps, pass through green belts and buildings, is it because of the large positioning error?
![Screenshot from 2022-09-21 09-50-04](https://user-images.githubusercontent.com/10770048/191396488-54118de3-ea8a-43b6-ae8e-743a84922a39.png)

**Comment by JokerJohn** [comment]
There may be two reasons,
1. The Google map itself is relatively rough
2. The origin GPS point  of LIO_SAM_6AXIS in the HKUST-CAMPUS dataset is not accurate
It is suggested that you can change to a dataset with better GPS for testing, which I will provide later.
