### ISSUE TITLE
请问 LIO-SAM-6AXIS有包含 LIO-SAM-6AXIS-INTENSITY通过反光强度识别回环这块的内容吗？

### ISSUE THREAD

**Issue by ZOUJIASHUAI** [JokerJohn/LIO_SAM_6AXIS#24]
@JokerJohn

**Comment by JokerJohn** [comment]
> @JokerJohn 

没有包涵这部分，因为对opencv版本有要求，整体比较笨重。

**Comment by ZOUJIASHUAI** [comment]
@JokerJohn 
请问对于16线或者32线的禾赛雷达加6轴IMU，您更推荐用哪个来建图相对较好呢？

**Comment by JokerJohn** [comment]
> @JokerJohn 
> 
> 请问对于16线或者32线的禾赛雷达加6轴IMU，您更推荐用哪个来建图相对较好呢？

自然是何塞32线。

**Comment by ZOUJIASHUAI** [comment]
@JokerJohn 
请问这两款雷达和6轴IMU是用LIO-SAM-6AXIS好还是 LIO-SAM-6AXIS-INTENSITY好？

**Comment by JokerJohn** [comment]
> @JokerJohn 
> 
> 请问这两款雷达和6轴IMU是用LIO-SAM-6AXIS好还是 LIO-SAM-6AXIS-INTENSITY好？

32线雷达，强度闭环检测预计效果一般，可以先跑liosam-6axis再尝试闭环增强。
