### ISSUE TITLE
The mapped point cloud starts to disappearing

### ISSUE THREAD

**Issue by Dhruv0208** [JokerJohn/LIO_SAM_6AXIS#27]
Hi, 
I had a question. I was testing the code, and observed that once all the data  from bagfile is published, the point cloud mapped starts to disappear. Can you tell why is that? And also, is there some parameter which can tweaked to delay it? And also which part of code takes care of it?
Thank You.

**Comment by JokerJohn** [comment]
Hi, @Dhruv0208 !
LIO_SAM is an online system, and its back-end optimization module has two threads, scan2map and loop detection. When the host's performance is relatively general, there is indeed insufficient computing power. For example, scan2map is over, but closed-loop detection is not yet.
I recommend two solutions:
1. Slow down when playing bag, such as rosbag playxx.bag -r 0.5
2. Modify the mapOptimizatioGps.cpp code, use deque to load the point cloud sent by the front end, and process it frame by frame in the while loop to turn it into an offline mapping system. The code writing method can refer to the pose_slam thread in my picture.

![image](https://user-images.githubusercontent.com/25702851/194138890-8e119a09-21ca-4008-9761-abe0a6c7f23a.png)
![image](https://user-images.githubusercontent.com/25702851/194138847-6c735112-ce3b-4688-9790-451015088bdf.png)

**Comment by Dhruv0208** [comment]
HI,
I tried using the first solution not much of a difference. Regarding the second solution, I am not using GPS info, will it still affect the output if I make changes?

**Comment by Dhruv0208** [comment]
![image](https://user-images.githubusercontent.com/51269047/194382319-282f0d0a-ca60-48e0-8ec2-282b7956e79d.png)
This is a output of the custom data. The bot is moving forward but the data from behind starts to disappear.

**Comment by JokerJohn** [comment]
@Dhruv0208 you'd better send me a data bag, and then I may configure the params for you!

**Comment by Dhruv0208** [comment]
@JokerJohn  sorry but I won't be able to share data. Can you tell what parameters are needed to be tweaked? I can try them by  myself.
