### ISSUE TITLE
[ERROR] system need to be initialized

### ISSUE THREAD

**Issue by sai2602** [JokerJohn/LIO_SAM_6AXIS#28]
Hi,

I am trying to run the the 6axis liosam for my setup (vlp16 with intel realsense for imu). The config file is updated to point to params_vlp.yaml. When I run the launch file, I get an error saying "system need to be initialized". May I know what additional initialization is expected?

**Comment by JokerJohn** [comment]
@sai2602 
you need to set useGPS as false in your config file
![image](https://user-images.githubusercontent.com/25702851/194510808-c03cc170-3de7-4569-ba3a-efc0b53f88bb.png)

**Comment by sai2602** [comment]
Sorry for the late reply. This solved the issue. Thanks for the update.
