### ISSUE TITLE
Using bag file created from save_map service.

### ISSUE THREAD

**Issue by Dhruv0208** [JokerJohn/LIO_SAM_6AXIS#29]
Can you guide how to visualize the bag file generated. The bag file generated show to tf data in it, due to which I am not able to visualize in the rviz.

**Comment by Dhruv0208** [comment]
Also, when calling the save map service, the global map with respect to lidar as well as imu, is not being saved, and they are also missing in the screenshot you have posted as an example.

**Comment by JokerJohn** [comment]
> Also, when calling the save map service, the global map with respect to lidar as well as imu, is not being saved, and they are also missing in the screenshot you have posted as an example.

use the newer version codes, 
![image](https://user-images.githubusercontent.com/25702851/198840810-aa3608cc-d53d-42c0-8d1c-f43019fc30f8.png)

**Comment by Dhruv0208** [comment]
Hi,
> Also, when calling the save map service, the global map with respect to lidar as well as imu, is not being saved, and they are also missing in the screenshot you have posted as an example.

The above issue, is still persistent can you help with it? 
  bool saveMapService(lio_sam_6axis::save_mapRequest& req, lio_sam_6axis::save_mapResponse& res)  The mentioned function in the mapOptimization.cpp file is not running.
