### ISSUE TITLE
How does the system initialize without the gravity direction indicated by the 9-axis IMU

### ISSUE THREAD

**Issue by jiejie567** [JokerJohn/LIO_SAM_6AXIS#3]
At first, thank you for publishing the great work, which is of great benefit to the poor people who only have   6-axis IMU like me. 
But I have a silly question, the lio-sam get the gravity direction by the  9-axis IMU when initializing. Thus if I apply your code in my project, will I need to keep my IMU horizontal？

**Comment by JokerJohn** [comment]
Of course, while you're collecting data, we strongly recommend that you keep the IMU horizontally stationary for a few seconds at the beginning.In addition, If you are using GPS, you also need to start collecting data when the GPS LLA covariance is small.

**Comment by JokerJohn** [comment]
> At first, thank you for publishing the great work, which is of great benefit to the poor people who only have 6-axis IMU like me. But I have a silly question, the lio-sam get the gravity direction by the 9-axis IMU when initializing. Thus if I apply your code in my project, will I need to keep my IMU horizontal？


Of course, while you're collecting data, we strongly recommend that you keep the IMU horizontally stationary for a few seconds at the beginning.In addition, If you are using GPS, you also need to start collecting data when the GPS LLA covariance is small.

**Comment by jiejie567** [comment]
@JokerJohn thank you for your quick and accurate answer！
