### ISSUE TITLE
用Livox horizon激光雷达出现以下问题

### ISSUE THREAD

**Issue by yijing2050** [JokerJohn/LIO_SAM_6AXIS#30]
[ERROR] [1666330391.719683054]: Point cloud ring channel not available, please configure your point cloud data!

**Comment by yijing2050** [comment]
感觉这个不适合Livox系列的雷达，或者livox驱动要改成适合Lio-sam处理的点云格式的输出数据

**Comment by JokerJohn** [comment]
> 感觉这个不适合Livox系列的雷达，或者livox驱动要改成适合Lio-sam处理的点云格式的输出数据

livox雷达虽然我私下已经做了适配，但是不想在代码中引入liovx driver相关的库，建议直接将livox点云转化为VLP这种格式的，再使用这个库即可。
