### ISSUE TITLE
Runing LIO_SAM_6AXIS on other dataset

### ISSUE THREAD

**Issue by MoonSheepJx** [JokerJohn/LIO_SAM_6AXIS#31]
您好，首先非常感谢您这么棒的工作
我想使用LIO_SAM_6AXIS在其它数据集上进行测试，并且开启GPS
1、但是我在运行时，发现了GPS与系统估计的状态差别较大，请问这是正常现象嘛，还是我的一些参数设置错误的问题？
![2022-11-02 20-13-50 的屏幕截图](https://user-images.githubusercontent.com/103256792/199488143-6b27db88-5c83-4c20-b7c0-b79f4abc485d.png)
2、我看了一下源代码和您在其他issue下的回答，貌似开启`useGPS`，一定是要等待GPS信号，才能初始化整个系统嘛，那如下这个现象就是正常的吧
![2022-11-02 20-14-04 的屏幕截图](https://user-images.githubusercontent.com/103256792/199489347-a17e2650-236e-4ca0-be93-c15de4183a60.png)

（我的配置文件如下，数据集为M2DGR）
![2022-11-02 20-14-29 的屏幕截图](https://user-images.githubusercontent.com/103256792/199489368-07be055f-83d4-4d96-be52-e7f0635bbf00.png)
再次非常感谢您的工作，非常希望您能给予一些帮助！

**Comment by MoonSheepJx** [comment]
您好，非常感谢您的及时回复与帮助，请问我可以这样理解吗
只有当gps拥有足够的帧数，初始化后，系统轨迹才受到gps的约束，此时的系统输出轨迹，才是结合了gps约束的轨迹，而当gps未初始化前，系统轨迹相当于纯LIO的轨迹

**Comment by JokerJohn** [comment]
> 您好，非常感谢您的及时回复与帮助，请问我可以这样理解吗 只有当gps拥有足够的帧数，初始化后，系统轨迹才受到gps的约束，此时的系统输出轨迹，才是结合了gps约束的轨迹，而当gps未初始化前，系统轨迹相当于纯LIO的轨迹

是的

**Comment by MoonSheepJx** [comment]
> > 您好，非常感谢您的及时回复与帮助，请问我可以这样理解吗 只有当gps拥有足够的帧数，初始化后，系统轨迹才受到gps的约束，此时的系统输出轨迹，才是结合了gps约束的轨迹，而当gps未初始化前，系统轨迹相当于纯LIO的轨迹
> 
> 是的

非常感谢您的帮助！
