### ISSUE TITLE
Type of LIDAR

### ISSUE THREAD

**Issue by Dhruv0208** [JokerJohn/LIO_SAM_6AXIS#32]
HI, I was testing the code for the data collected by using a Below Horizon type OS1 Lidar, Can you suggest any changes to make it work?

**Comment by JokerJohn** [comment]
> HI, I was testing the code for the data collected by using a Below Horizon type OS1 Lidar, Can you suggest any changes to make it work?
> 
> 

Just check the point cloud type OusterPointXYZIRT in imageProjection.cpp

**Comment by Dhruv0208** [comment]
Sorry, but couldn't understand. Is there some changes need to be made or change some flag from false to true?

**Comment by JokerJohn** [comment]
> Sorry, but couldn't understand. Is there some changes need to be made or change some flag from false to true?

it depends on your lidar driver.  check your point cloud structure and the timestamp of each point.
