### ISSUE TITLE
Adaptable for solid state lidar?

### ISSUE THREAD

**Issue by sai2602** [JokerJohn/LIO_SAM_6AXIS#35]
Hello @JokerJohn,

Thank you for the great work. I tried this with my vlp16 and it worked great. I wanted to know if this is also compatible with a solid state lidar like the L515? What would be the configuration changes needed if so since the velodyne pointcloud clouds have a format of XYZIRT?

**Comment by JokerJohn** [comment]
> Hello @JokerJohn,
> 
> Thank you for the great work. I tried this with my vlp16 and it worked great. I wanted to know if this is also compatible with a solid state lidar like the L515? What would be the configuration changes needed if so since the velodyne pointcloud clouds have a format of XYZIRT?

Unfortunately, we don't have an adaptation for solid-state lidar.
