### ISSUE TITLE
PCD maps not being saved

### ISSUE THREAD

**Issue by Dhruv0208** [JokerJohn/LIO_SAM_6AXIS#36]
Hi, regarding a previous issue: https://github.com/JokerJohn/LIO_SAM_6AXIS/issues/29

The above issue, is still persistent can you help with it?
bool saveMapService(lio_sam_6axis::save_mapRequest& req, lio_sam_6axis::save_mapResponse& res) The mentioned function in the mapOptimization.cpp file is not running.

**Comment by hamkewl** [comment]
Hi, 

Have you ever tried rosservice?
You can save pcd with `$ rosservice call /lio_sam/save_map`.

By the way, the original repository describes the command using rosservice, but it seems that the downsampling process by voxel grid filter is omitted in this repository. If you want to do downsampling, you need to do it separately.
