### ISSUE TITLE
password of GT

### ISSUE THREAD

**Issue by coolaogege** [JokerJohn/LIO_SAM_6AXIS#38]
Thank you for your nice work! 
I have tested this code , it works perfectly ！Now i want to evaluate this trajectory by evo. But i can not find this password of GT. Can you tell me the password？By the way,  How are the ground truth values obtained for these two datasets？
![2022-12-02 19-08-30 的屏幕截图](https://user-images.githubusercontent.com/87416237/205282118-5aa4e58d-e11d-4675-9275-b9caa570356b.png)

**Comment by JokerJohn** [comment]
[link](https://hkustconnect-my.sharepoint.com/:t:/g/personal/xhubd_connect_ust_hk/ESoJj5STkVlFrOZruvEKg0gBasZimTC2HSQ2kqdIOWHiGg?e=Hup1fT)

you can try the password 123

**Comment by JokerJohn** [comment]
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/25702851/205438335-e23e54a0-159e-436b-8e00-a90a20dff8f5.png">

**Comment by coolaogege** [comment]
> [link](https://hkustconnect-my.sharepoint.com/:t:/g/personal/xhubd_connect_ust_hk/ESoJj5STkVlFrOZruvEKg0gBasZimTC2HSQ2kqdIOWHiGg?e=Hup1fT)
> 
> you can try the password 123

Thanks, I can get GT!
