### ISSUE TITLE
imu_type in yaml 

### ISSUE THREAD

**Issue by 0NNS0** [JokerJohn/LIO_SAM_6AXIS#39]
感谢大佬的开源！好像发现了个小问题：

yaml文件内的imu_type应修改为imuType。
因为utility.h使用的是nh.param<int>("lio_sam_6axis/imuType", imuType, 0);

**Comment by JokerJohn** [comment]
> 感谢大佬的开源！好像发现了个小问题：
> 
> yaml文件内的imu_type应修改为imuType。 因为utility.h使用的是nh.param("lio_sam_6axis/imuType", imuType, 0);

感谢反馈，我在测试的时候一般使用的默认的yaml文件，其他配置还未同步进行更改。
