### ISSUE TITLE
DataSaver eigen new 没有对齐

### ISSUE THREAD

**Issue by vell001** [JokerJohn/LIO_SAM_6AXIS#42]
lio_sam_6axis_mapOptmization: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:128: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 32>::plain_array() [with T = double; int Size = 4; int MatrixOrArrayOptions = 0]: Assertion `(internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) & (31)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.

dataDaver使用了Eigen的数据结构作为成员变量，需要加上EIGEN_MAKE_ALIGNED_OPERATOR_NEW 进行对齐，要不然new的时候会报错
![image](https://user-images.githubusercontent.com/4609672/212843721-eb290bc8-4a99-4958-aacd-aa4746021888.png)

![image](https://user-images.githubusercontent.com/4609672/212843656-7c21265d-63c9-4b61-adb6-bea65b08433e.png)

**Comment by JokerJohn** [comment]
感谢反馈，下波更新修复这个问题。
