### ISSUE TITLE
点云到谷歌地图

### ISSUE THREAD

**Issue by qqstar-423** [JokerJohn/LIO_SAM_6AXIS#45]
感谢你们伟大的开源！

有一个代码之外的问题想要请问一下，我看到您有一个hkust.gif将点云地图映射到了谷歌地图上，这实在太酷辣！但我搜索了很久没有找到相关的教程，我想请问一下你们用的是什么工具呢？

![2023-04-25 22-06-14屏幕截图](https://user-images.githubusercontent.com/85664678/234302340-e635a091-72a4-45d6-a29a-fb6de5ba04ba.png)

**Comment by JokerJohn** [comment]
仓库中有一个rviz-satellite 的ros插件，你需要先安装这个。然后修改launch文件中你的地图起点gnss坐标，


    
    <node pkg="rostopic" type="rostopic" name="fake_gps_fix"
          args="pub gps/fix sensor_msgs/NavSatFix '{ header: auto, latitude: 22.3387279108228, longitude: 114.263622199692, altitude:  87.7310562}'"
          output="screen"/>

**Comment by qqstar-423** [comment]
感谢您的回复！我按照rviz-satellite的README修改了gps初始配置文件，成功的加载了卫星图，但是我发现我的起点会随着时间而不断的变换，这是为什么呢？我的rviz配置如下图，GPS话题为/fix410cff
![111](https://user-images.githubusercontent.com/85664678/234471658-18ca07d6-d15c-4843-bd79-69a6435a8416.png)

**Comment by JokerJohn** [comment]
修改robotFrame为你的body系，
<img width="383" alt="image" src="https://user-images.githubusercontent.com/25702851/234527549-29fb419e-06f0-4435-8ed9-083e3f4fccb1.png">

**Comment by qqstar-423** [comment]
感谢您的回答！我已成功运行（虽然地图有点简陋），很抱歉问之前没有好好看您给出的源码和readme，再次感谢！

**Comment by JokerJohn** [comment]
> 感谢您的回答！我已成功运行（虽然地图有点简陋），很抱歉问之前没有好好看您给出的源码和readme，再次感谢！

看你的截图，地图简陋的原因是你用的osm地图吧，你要用google map那种的话，需要换个一个api，比如Tomtom的map

**Comment by G7-3208** [comment]
您好 我启动的时候会出现[ERROR] [1749802616.201641881]: PluginlibFactory: The plugin for class 'rviz_plugins/AerialMapDisplay' failed to load.  Error: MultiLibraryClassLoader: Could not create class of type rviz::AerialMapDisplay
请问该如何解决

**Comment by JokerJohn** [comment]
@bobo7727 可以将起点的初始noise设置小一点，那么就会相当于固定住起点。比如这个1e-4变成1e-6

<img width="1083" alt="Image" src="https://github.com/user-attachments/assets/0cafc255-ab20-497b-9e1c-80a55918e480" />

**Comment by bobo7727** [comment]
感觉像是地图插件一直把起点锚定到正中间，整个点云地图也随着地图块加载而变化，请问如何让点云地图和卫星地图固定，不随之变化？

![Image](https://github.com/user-attachments/assets/9391221b-8f7c-45ba-be8f-5eb1a0c85a87)

![Image](https://github.com/user-attachments/assets/c1885400-cbce-43d7-9e0e-68ebfca3f2d0)

![Image](https://github.com/user-attachments/assets/61689bf1-1c46-4beb-8dc1-44b7e157145a)

**Comment by bobo7727** [comment]
@JokerJohn 您好，是我这边操作有点问题。我重新编译您代码中的rviz_satellite模块（覆盖之前命令行安装的rviz_satellite）使用后，恢复正常，非常感谢您的回复！
