### ISSUE TITLE
how to compare your pcd map with google map?

### ISSUE THREAD

**Issue by pauls0323** [JokerJohn/LIO_SAM_6AXIS#47]
Hello,JokerJohn.
      Thanks for your work.I am working with lio-sam.My pcd map have no flat ground point cloud.In your work,you path is able to match with satelite map. So,I wonder how to make this.

**Comment by pauls0323** [comment]
您好：
 感谢您能分享您的工作成果。我也在使用lio-sam，但是我建出来的点云地图，地面是不平坦的。我想知道您是如何做到使用自己的点云地图和谷歌地图做对比。谢谢！

**Comment by JokerJohn** [comment]
按readme跑代码即可，点云投影到googlemap上，本身就是2d的，不必纠结。
