### ISSUE TITLE
您好！关于6轴IMU的标定？Calibration of 6 axis IMU

### ISSUE THREAD

**Issue by wangxb-code** [JokerJohn/LIO_SAM_6AXIS#5]
您好，请问一下如何将六轴IMU的数据转换为sensor_msgs::Imu类型，因为目前对IMU进行标定的算法都是需要sensor_msgs::Imu数据类型，因为六轴IMU的数据只有angular_velocity和linear_acceleration，没有orientation，该怎么求出orientation进行标定呢？求解惑。Hello, how to convert the data of the six-axis IMU to sensor_msgs :: Imu? Because the current calibration algorithm for IMU requires sensor_msgs :: imu data type. Because the six-axis IMU data only has angular_velocity and linear_acceleration, but no orientation, how to calculate the orientation for calibration? Seek to reassure.

**Comment by JokerJohn** [comment]
i mentioned before that you need to write a ros driver to parse your imu raw data from your serial port and published them.  As for the calibration, you first need to know about the extrinsics between IMU and lidar, and the intrinsics of IMU. Then you can search for other repos in github to solve your problem.
