### ISSUE TITLE
GT of 20220216_garden_day.txt 

### ISSUE THREAD

**Issue by huiyan-dev** [JokerJohn/LIO_SAM_6AXIS#51]
GT of 20220216_garden_day.txt need password to verify, would you please provide the GT for me?

**Comment by JokerJohn** [comment]
> GT of 20220216_garden_day.txt need password to verify, would you please provide the GT for me?

just click this link [GT_garden_day](https://hkustconnect-my.sharepoint.com/:t:/g/personal/xhubd_connect_ust_hk/Ea-e6VPaa59Br-26KAQ5IssBm2_0t6nCjOghUMZzBC_-lw?e=46neFZ)

**Comment by huiyan-dev** [comment]
That help me a lot, thank you .
