### ISSUE TITLE
Dataset availability through dropbox/google drive

### ISSUE THREAD

**Issue by juliangaal** [JokerJohn/LIO_SAM_6AXIS#52]
I am trying to access the hkust...full dataset (used for main .gif file?) to test some changes to the gps tools. I was wondering if the link to google drive was intentional, when the label is "dropbox"? I sent an access request through google drive a couple weeks ago

**Comment by JokerJohn** [comment]
> I am trying to access the hkust...full dataset (used for main .gif file?) to test some changes to the gps tools. I was wondering if the link to google drive was intentional, when the label is "dropbox"? I sent an access request through google drive a couple weeks ago

There's a typo; I just forgot to edit it. However, Google Drive doesn't require permissions; you can download directly.
<img width="1122" alt="image" src="https://github.com/JokerJohn/LIO_SAM_6AXIS/assets/25702851/0e56c9fd-8af5-45df-a779-04ae35e9c02d">

**Comment by juliangaal** [comment]
That's strange. Using this link

![origin](https://github.com/JokerJohn/LIO_SAM_6AXIS/assets/22290570/7b39f172-68e9-467b-a8e9-93896eb709df)

I arrive straight at

![access](https://github.com/JokerJohn/LIO_SAM_6AXIS/assets/22290570/5e342fc5-9160-4811-9026-f96f9808bc84)

Could you check the settings?

**Comment by JokerJohn** [comment]
> That's strange. Using this link
> 
> ![origin](https://user-images.githubusercontent.com/22290570/256638740-7b39f172-68e9-467b-a8e9-93896eb709df.png)
> 
> I arrive straight at
> 
> ![access](https://user-images.githubusercontent.com/22290570/256638785-5e342fc5-9160-4811-9026-f96f9808bc84.png)
> 
> Could you check the settings?

here is a one drive link.  [Download](https://hkustconnect-my.sharepoint.com/:u:/g/personal/xhubd_connect_ust_hk/Eea0g76yXehDt4asNoL6l14B6lEIX4eVX6aSG-CsnVUCjg?e=N2cSZx)

**Comment by juliangaal** [comment]
worked like a charm, thank you!
