### ISSUE TITLE
imu精度问题

### ISSUE THREAD

**Issue by NoMoreBeauty** [JokerJohn/LIO_SAM_6AXIS#64]
@JokerJohn 您好，我想请问一下，imu的最低精度要求是多少，我的imu精度比较低，现在会跑飞，我想确认下是不是imu的问题
另外我的部署环境是imu系相对于Lidar系绕z轴顺时针旋转了90°，imu里面加速度系和角速度系是对齐的，请问旋转矩阵是不是设置成
extrinsicRot: [0, -1, 0,
                  1, 0, 0,
                  0, 0, 1]

**Comment by JokerJohn** [comment]
对IMU没有最低精度要求。低成本的也能跑，比如livox自带的这种就行，但效果必然会受到影响。
“我的imu精度比较低，现在会跑飞”，描述下怎么跑飞的，比如一开始就直接飞了，还是成功走了一小段再飞？最好给个截图才方便判断原因。
LIO飞的核心原因一般有以下几点。
1.外参，R更重要，直接导致飞 or 不飞 或者严重重影。LIDAR和IMU需要提前做好外参标定. 
2.点云时间戳，确保点云中每个点的相对时间在0-0.1s内，注意时间单位为秒（fastlio为ms，要区分开）.
3.IMU噪声，可以根据艾伦方差标定的结果，放大100倍尝试。越差的IMU噪声设置越大，比如0.1. 可以逐个量级尝试下，类似calbir中设置IMU噪声.
