### ISSUE TITLE
gps与slam对齐

### ISSUE THREAD

**Issue by fyyink** [JokerJohn/LIO_SAM_6AXIS#66]
如何实现的gps里程计与slam里程计对齐

**Comment by JokerJohn** [comment]
看这个[issue](https://github.com/JokerJohn/LIO_SAM_6AXIS/issues/58)

**Comment by zhao-zhibo** [comment]
@fyyink 我觉得这个[issur](https://github.com/JokerJohn/LIO_SAM_6AXIS/issues/50)里面反映的问题，也比较清晰，介绍了gps和lio的里程计是怎么对齐的。我也在看这部分内容，学习如何对齐的，issue里面写是用因子图优化的方式对齐了这两个坐标系。
