### ISSUE TITLE
请问怎么把组合导航结果投影到激光地图坐标上？

### ISSUE THREAD

**Issue by JiangWeiHn** [JokerJohn/LIO_SAM_6AXIS#69]
我们想确定imu+rtk组合导航的精度，就想对比和lio_sam的输出，采用lio_sam_6axis 输出地图，采用liorf_localization加载地图输出激光+imu的输出结果，ENU的原点采用origin.txt输出结果。我们采集的测试点都是静止状态下的点。rtk的输出方差都在4cm之内，但和激光地图的对比结果，最大在0.8m左右，平均在0.3m左右，为啥会有这么大的误差呢？是不是我从组合导航的输出直接和激光雷达的输出对比不对？还需要怎样的转换？

**Comment by JokerJohn** [comment]
@JiangWeiHn 不清楚liorf_localization怎么做的。静止状态下，LIO结果不如预期很正常，可以详细研究下IMU噪声模型以及重力约束。

**Comment by JiangWeiHn** [comment]
好的，谢谢，我再研究下
