### ISSUE TITLE
Compile error with GeographicLib

### ISSUE THREAD

**Issue by samsdolphin** [JokerJohn/LIO_SAM_6AXIS#70]
Hi authors, thanks for your great work.

I am using Ubuntu 20.04 and ROS noetic. I try to compile the code but come with error.
> GeographicLib/LocalCartesian.hpp: No such file or directory

This is weird as the package `GeographicLib` is already included in the path and the CMakeLists.txt. So what I did is to change

> #include <GeographicLib/Geocentric.hpp>
#include <GeographicLib/LocalCartesian.hpp>

to

> #include <Geocentric.hpp>
#include <LocalCartesian.hpp>

and this problem is fixed.

**Comment by JokerJohn** [comment]
thanks, xiyuan
