### ISSUE TITLE
关于updateInitialGuess 函数的问题

### ISSUE THREAD

**Issue by JiangWeiHn** [JokerJohn/LIO_SAM_6AXIS#73]
请问作者，在updateInitialGuess 函数中，if(GPS)程序最后是否需要个return?,因为在不用GPS的初始化第一帧完成后就return了？

![832CB44F-A9D1-4c4e-B35D-3D1C059DFFA8](https://github.com/JokerJohn/LIO_SAM_6AXIS/assets/24561984/009cf9d5-3f35-482b-b715-f87bd053f5de)

**Comment by JokerJohn** [comment]
@JiangWeiHn This piece of code is actually unnecessary as the initialization process is not conducted here. It can be safely ignored.

**Comment by JiangWeiHn** [comment]
好的，谢谢
