### ISSUE TITLE
点云和gps轨迹没有对齐

### ISSUE THREAD

**Issue by MasonMax** [JokerJohn/LIO_SAM_6AXIS#81]
点云一开始和gps轨迹、google map没有对齐
![image](https://github.com/JokerJohn/LIO_SAM_6AXIS/assets/44404944/f33c119d-d256-4a8d-b61b-bf95a8fbdf13)
跑到绿色框的位置突然就对齐了
![image](https://github.com/JokerJohn/LIO_SAM_6AXIS/assets/44404944/4f6a30f7-ae94-41e3-8f0d-f64196618088)
然后就正常了
![image](https://github.com/JokerJohn/LIO_SAM_6AXIS/assets/44404944/27a13260-db66-4cb6-b74f-3b1275c69099)
想问一下为什么会这样

**Comment by JokerJohn** [comment]
找一下gps相关的历史issue。为了避免前期因为gps观测不稳定带来融合轨迹出错的情况，前期是批量处理的，等足够的gps数据进来了，才批量优化
